### ISSUE TITLE
[Angel's Bio] Free energy via cellulose reactions

### ISSUE THREAD

**Issue by pjf** [boweiliu/Marathon#3]
It looks like one can create free energy via cellulose reactions unlocked with the green algae tech. In particular:

- 12 raw wood to craft 48 cellulose fibre
- 48 cellulose fibre to craft 8 wood pellets
- 8 wood pellets to craft 4 wood bricks

Inputs: 12 raw wood @ 2MJ ea = 24 MJ
Outputs: 4 wood bricks @ 12MJ ea = 48MJ
Result: Total energy value from raw wood *doubled*.

The free energy seems to arrive in the cellulose fibre to wood pellets step. The recipe is 12 fibre (12 x 500kJ = 6MJ) to 2 pellets (2 x 6MJ = 12MJ). This then carries over to the wood pellets to brick recipe.

Halving the fuel value of wood pellets and wood bricks should make the energy chain balance again.

Alternatively, I've spotted a comment in the code that suggests the energy increase may be intentional. If that's the case, I'd suggest halving the energy value of pellets, but keeping bricks as-is. Wood bricks are only used as fuel, but the player has little reason to craft them if pellets have the same energy value.

Many thanks again for a great mod!

~ Paul

**Comment by boweiliu** [comment]
I actually looked into this for quite a long time. I believe the energy used to run the machines to do this assembly chain outweighs the free energy returned, unless there is a bug somewhere. Yes, it is indeed intentional that burning raw wood logs is not as efficient as processing them into pellets/bricks and then burning (there should be an incentive to use that production chain). However note that green algae to cellulose costs CO2 which requires a fair amount of energy input (burning pellets). 

It is also intentional that by the time you have efficiency modules, algae -> bricks will be a source of free energy. But by then you probably have solar/nuclear so it doesn't really matter.

I personally actually find bricks quite useful, solely for the fact that you can achieve higher throughput -- they're better than cokecoal in terms of energy density per full belt, and so should come with a slight efficiency penalty. it's also useful for more effectively daisy chaining boilers if you have that kind of boiler setup.

**Comment by pjf** [comment]
@boweiliu : Awesome! I like the idea of rewarding the player for spending extra time doing pre-processing of materials, which is probably while I'm really loving Angel's refining so much. I'm guessing the energy boost for processing coke is also intentional?

I'm making a bunch of notes as I go, and these will probably end up as a guide or other public document at some point. Would you like me to create them in the [project wiki](https://github.com/boweiliu/Marathon/wiki) so they're easy to find, or should I be doing that elsewhere to keep your administrative overheads lower? (Anything I make will be under a permissive and free license, so you'll be able to integrate them into your own docs if you wish.)

Many thanks again, and thanks for being so responsive with all my reports, questions, and ideas!

~ Paul
